travis:
  secure:
    BINSTAR_TOKEN: XEJzWDjRwn2O1n2pC7tHIHOF4z9dEwIlFn9PhukX4AvojVXgGEbw+9wN6t/GyRkuDyiAzN7EuJxyRcSmSLKY6Q1PNAV70ZwcqEfMg6gepUp8qu0sskKiPitMgTj4+ox1oIc52wlBY60jfQSqx1HoxntDY6yYg/+w53dRB44MIrN/qyASP+H1VEMJ+jXbviE4nf6a7SkTwlzmuHOO8f3iuyzCJgC3HhtSXMRan5bElBuvZLBOu/f8Dpy4v2cmB1+U5tL9e2ITTKOVQYxSQIRuk/aU1nPwO9f55LFx463D4wJuPadpGwewxG0mWPvwLUlsVYNoG76bokFg5Fbl7GkRY0yFsJvozDPW+olRU54EGaqA60wfBtbHkkY+FdHInmx+kNrwEdpbAvCHDzVGFwXJyKHBQvv8x+n1mR149TIdTtiV/Ptov2hxg6YE7zMcDUPLkNSwJdY76m+oPXtJ2UnGsc7Wb+BhCX8TuCnTrvAjbZkYs8bVX4MHMzE1n+EczkxlmFONLWMuB6iF9NlKjxrz1ASfAoyr97um0q8p39yfUYf38G629mBKzt/aO1EswCZsMRtr5LiwtSylcVfN0YKzXkGL75KNoUU5gJE2yOnWGnUMAtr8mSv1MY+gv1EnQCB4YT8Hrznhnunq8Bik79RZ7oB4/+/tSFy7RJKaqnlyi5w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
